[build]
  command = "build.sh"
  publish = "public"
  functions = "functions"

[build.environment]
  PHP_VERSION = "8.3"
  NODE_VERSION = "16"
  COMPOSER_VERSION = "2.2.6"

[context.production.environment]
  APP_ENV = "production"
  APP_DEBUG = "false"
